# Generated by Django 6.0.2 on 2026-02-16 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Candidate Email', max_length=254)),
                ('designation', models.CharField(choices=[('Sales Manager', 'Sales Manager'), ('Assistant Sales Manager', 'Assistant Sales Manager'), ('Agent Relationship Manager', 'Agent Relationship Manager'), ('HR Manager', 'HR Manager'), ('HR Executive', 'HR Executive'), ('IT Executive', 'IT Executive'), ('Sales Executive', 'Sales Executive'), ('IT Sales Manager', 'IT Sales Manager'), ('IT Manager', 'IT Manager'), ('Social Media Manager', 'Social Media Manager'), ('Trainer', 'Trainer')], max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_content', models.TextField(help_text='Custom content or generated HTML')),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
